### ISSUE TITLE
Will this library be further developed?

### ISSUE THREAD

**Issue by purepani** [calebfletcher/foc#1]
Title. I've been looking for FOC libraries in the rust ecosystem, and there don't seem to be any that are supported; I would consider rewriting my own, but I am not super experienced with motor control, so it would be better if this library could be further developed.
Alternatively, I would like to ask what the current state of the library is. As far as I can tell, the FOC calculations are implemented, but there's little to no embedded-hal implementation. Is that accurate? If so, I'd feel more comfortable using this library as a base.

**Comment by calebfletcher** [comment]
I noticed a similar gap in the available libraries, which is why I created this library to begin with. You are correct that at the moment the basic FOC algorithms are implemented, but that there isn't much in the way of an all-in-one FOC controller that you can just drop in to your system.

I'm currently in the process of bringing up some hardware so that I can more actively work on this and test it, so there should be some more activity in this repo happening soon. Embedded-hal integration is definitely something I would like to implement at some point, however I anticipate some issues due to the traits that are available and their support in the hardware-specific crates. The interfaces that FOC would need are:

- PWM - There is an [embedded-hal trait](https://docs.rs/embedded-hal/latest/embedded_hal/pwm/trait.SetDutyCycle.html) but so far only [one](https://github.com/search?q=org%3Astm32-rs+lang%3Arust+SetDutyCycle&type=code) STM32 crate has implemented it and [Embassy has no support at all](https://github.com/search?q=repo%3Aembassy-rs%2Fembassy%20SetDutyCycle%20lang%3Arust&type=code).
- ADCs for current monitoring - The embedded_hal trait was removed prior to the v1.0 release, and hasn't had much new development since.
- Encoders - While there are low-level SPI/I2C traits in embedded_hal, we would probably need something higher-level (like an `Encoder` trait) so that we don't have to put all the different encoder driver implementations in this crate.

Given this, I'm not sure how feasible it would be to support embedded-hal. At least in the short term, I would be looking at keeping this crate to be more IO-agnostic. The API is going to look roughly like the [Foc struct](https://docs.rs/foc/latest/foc/struct.Foc.html), which currently is just a prototype for me to plan around (you can't actually construct it). Based on that API, you get a single method that takes in your encoder reading, your current readings, and your desired torque, and then produces the PWM values you need to set on your PWM controller. This design would allow people to use it with minimal integration effort, while also allowing people to use it on any microcontroller they want.

**Comment by purepani** [comment]
Hey @Ben-PH
Here are the references I found for ADC stuff
https://github.com/rust-embedded/embedded-hal/issues/377
https://github.com/rust-embedded/embedded-hal/pull/569

**Comment by calebfletcher** [comment]
With 0.3.0 of this crate being released an overall FOC controller which wraps all of the underlying algorithms into a single controller is available, which addresses your original question of having something more than just the raw algorithms. For the `embedded_hal` integration, I have created a tracking issue https://github.com/calebfletcher/foc/issues/3.
